services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
    volumes:
      - ../../src:/usr/src/app/src
    ports:
      - 3000:3000
    depends_on:
      - database
