services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
    volumes:
      - ../../src:/usr/src/app/src
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
